### ISSUE TITLE
OpenModsLib Server Crash on Join

### ISSUE THREAD

**Issue by enterprise12nx** [OpenMods/OpenModsLib#32]
I have been updating my modpack to 1.7.10
After hours of adding/removing mods, i found that just OpenModsLib alone causes a crash.
It happens upon trying to join the world.

http://pastebin.com/jj1pHsVD

**Comment by boq** [comment]
Probably version mismatch. But I'm guessing, since you gave absolutely no information about used versions. 

Also, you are using Bukkit/Spigot. It's also worth mentioning in future reports. Actually, crash occurs between vanilla and bukkit patched code, so I suggest investigating this.

While we have very limited support for non-vanilla server, I already know it's start fine. So it's very probably problem is on your side.

**Comment by cjcoley2** [comment]
i have the same issue and i can give you what it if you need me to
this is the server console if you would like me to send you a photo or copy of the crash report file i can


https://clients.mcprohosting.com/knowledgebase.php?action=displayarticle&id=182
02.04 13:35:25 [Multicraft] Server stopped 02.04 13:35:23 [Multicraft] Not restarting crashed server. 02.04 13:35:23 [Multicraft] Error writing to server: [Errno 32] Broken pipe 
02.04 13:35:23 [Multicraft] Error writing to server: [Errno 32] Broken pipe 
02.04 13:35:23 [Multicraft] Stopping server! 
02.04 13:35:23 [Multicraft] Server shut down 
02.04 13:35:22 [Server] INFO The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded. 
02.04 13:35:22 [Server] INFO Holder lookups applied 
02.04 13:35:22 [Server] INFO Applying holder lookups 
02.04 13:35:22 [Server] INFO Unloading dimension 1 02.04 
13:35:22 [Server] INFO Unloading dimension -1 02.04 
13:35:22 [Server] INFO Unloading dimension 0 02.04 
13:35:22 [Server] INFO Saving chunks for level 'DIM-1'/Nether 02.04 
13:35:22 [Server] INFO Saving chunks for level 'DIM1'/The End 02.04 
13:35:22 [Server] INFO Saving chunks for level 'Toast'/Overworld 02.04 
13:35:22 [Server] INFO Saving worlds 02.04 
13:35:22 [Server] INFO Saving players 02.04 
13:35:22 [Server] INFO Disabling WorldEdit v6.0;3342-78f975b9 02.04 
13:35:22 [Server] INFO Disabling Essentials v2.13.1 02.04 
13:35:22 [Server] INFO Disabling EssentialsChat v2.13.1 02.04 
13:35:22 [Server] INFO Disabling EssentialsProtect v2.13.1 02.04 
13:35:22 [Server] INFO Disabling EssentialsAntiBuild v2.13.1 02.04 
13:35:22 [Server] INFO Disabling EssentialsSpawn v2.13.1 02.04 
13:35:22 [Server] INFO Stopping server 02.04 
13:35:22 [Server] ERROR This crash report has been saved to: /./crash-reports/crash-2015-04-02_13.35.22-server.txt 02.04 
13:35:22 [Server] INFO ... 12 more 02.04 
13:35:22 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:174) ~[launchwrapper-1.9.jar:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276) ~[launchwrapper-1.9.jar:?] 02.04 
13:35:22 [Server] INFO at openmods.OpenModsClassTransformer.transform(OpenModsClassTransformer.java:230) ~[OpenModsClassTransformer.class:?] 02.04 
13:35:22 [Server] INFO at openmods.OpenModsClassTransformer.tryApplyContextWrapper(OpenModsClassTransformer.java:247) ~[OpenModsClassTransformer.class:?] 02.04 
13:35:22 [Server] INFO at openmods.asm.VisitorHelper.apply(VisitorHelper.java:29) ~[OpenModsLib-1.7.10-0.6.jar:?] 02.04 13:35:22 [Server] INFO at openmods.OpenModsClassTransformer$8.createVisitor(OpenModsClassTransformer.java:250) ~[OpenModsClassTransformer$8.class:?] 02.04 
13:35:22 [Server] INFO at openmods.context.ContextClassTransformer.<init>(ContextClassTransformer.java:65) ~[ContextClassTransformer.class:?] 02.04 
13:35:22 [Server] INFO at org.objectweb.asm.ClassVisitor.<init>(Unknown Source) ~[asm-all-4.1.jar:4.1] 02.04 13:35:22 [Server] INFO Caused by: java.lang.IllegalArgumentException 02.04 13:35:22 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) ~[MinecraftServer.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) ~[nc.class:?] 02.04 13:35:22 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:247) ~[ej.class:?] 02.04 13:35:22 [Server] INFO at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:70) ~[nn.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:130) ~[nn.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.management.ServerConfigurationManager.attemptLogin(ServerConfigurationManager.java:521) ~[oi.class:?] 02.04 
13:35:22 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72] 02.04 
13:35:22 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72] 02.04 13:35:22 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188) ~[launchwrapper-1.9.jar:?] 02.04 
13:35:22 [Server] INFO java.lang.ClassNotFoundException: net.minecraft.server.management.ItemInWorldManager 02.04 
13:35:22 [Server] ERROR Cause of unexpected exception was 02.04 
13:35:22 [Server] INFO ... 10 more 02.04 
13:35:22 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72] 02.04 13:35:22 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72] 02.04 13:35:22 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:174) ~[launchwrapper-1.9.jar:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276) ~[launchwrapper-1.9.jar:?] 02.04 
13:35:22 [Server] INFO at openmods.OpenModsClassTransformer.transform(OpenModsClassTransformer.java:230) ~[OpenModsClassTransformer.class:?] 02.04 
13:35:22 [Server] INFO at openmods.OpenModsClassTransformer.tryApplyContextWrapper(OpenModsClassTransformer.java:247) ~[OpenModsClassTransformer.class:?] 02.04 
13:35:22 [Server] INFO at openmods.asm.VisitorHelper.apply(VisitorHelper.java:29) ~[OpenModsLib-1.7.10-0.6.jar:?] 02.04 
13:35:22 [Server] INFO at openmods.OpenModsClassTransformer$8.createVisitor(OpenModsClassTransformer.java:250) ~[OpenModsClassTransformer$8.class:?] 02.04 
13:35:22 [Server] INFO at openmods.context.ContextClassTransformer.<init>(ContextClassTransformer.java:65) ~[ContextClassTransformer.class:?] 02.04 
13:35:22 [Server] INFO at org.objectweb.asm.ClassVisitor.<init>(Unknown Source) ~[asm-all-4.1.jar:4.1] 02.04 
13:35:22 [Server] INFO Caused by: java.lang.IllegalArgumentException 02.04 13:35:22 [Server] INFO ... 10 more 02.04 13:35:22 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72] 02.04 13:35:22 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72] 02.04 13:35:22 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188) ~[launchwrapper-1.9.jar:?] 02.04 13:35:22 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.management.ItemInWorldManager 02.04 13:35:22 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) ~[MinecraftServer.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) ~[nc.class:?] 02.04 13:35:22 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:247) ~[ej.class:?] 02.04 13:35:22 [Server] INFO at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:70) ~[nn.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:130) ~[nn.class:?] 02.04 
13:35:22 [Server] INFO at net.minecraft.server.management.ServerConfigurationManager.attemptLogin(ServerConfigurationManager.java:521) ~[oi.class:?] 02.04 
13:35:22 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/management/ItemInWorldManager 02.04 
13:35:22 [Server] ERROR Encountered an unexpected exception 02.04 
13:35:22 [Server] INFO openmods.OpenModsClassTransformer.tryApplyContextWrapper(OpenModsClassTransformer.java:246): Adding context wrappers to mx(net.minecraft.server.management.ItemInWorldManager) 02.04 13:35:22 [Server] INFO UUID of player Synthos_Colton is 7c2bf2e6-aecf-44d9-886e-072614862ab9

**Comment by boq** [comment]
Oh, now I see what happening (but I had to spend some time to clean those scrambled logs). It's caused by ancient libraries in Cauldron. I guess I can work around that.
