### ISSUE TITLE
Crash when starting server

### ISSUE THREAD

**Issue by fanzypantz** [OpenMods/OpenModsLib#39]
I'm trying to run a server with all the open mods on it and the client version runs completely fine. The server however stops pretty fast after starting it up. I cant figure out if its missing anything or if there is anything out of date. All the openmod mods are up to date. 

Pastebin of the log; http://pastebin.com/E8ZEwxjn

Screenshot of all the mods(customized SolitaryCraft pack); http://puu.sh/goNGc/07f459a45a.png

**Comment by boq** [comment]
Looks like #34 and #35 duplicate, which was (probably) caused by corrupted installation

**Comment by fanzypantz** [comment]
Its really hard to use a corrupt installation universal.jar version of forge. I'm using the latest 1.7.10 version. Do I really need to do it the hard way when all the other mods work with the universal?

**Comment by boq** [comment]
I never said anything about actual forge.jar. I meant duplicated files, jar mods and misbehaving mods and launchers.

I can't fix crashes that I can't reproduce. Previous issues suggest that it was probably user error, but I never got clear description what was wrong. So unfortunately, I can't help you.

You can try with most recent snapshots from [here](http://www.openmods.info:8080/) (on test world of course), since it may give you clearer logs.

**Comment by fanzypantz** [comment]
Yeah this is true, I am currently adding every single mod back into the server one by one, restarting the server each time. I'll come back if I figure out what was wrong.

**Comment by boq** [comment]
Hey, do you still have this issue? I'm really trying to get any hint that I can, so I can at least have clear fix instructions.

If you still can reproduce it, can you start java with `-verbose:class` argument?

**Comment by fanzypantz** [comment]
I'm not really sure, I moved all the mods over to a new server and checked the mods so no client mods where on the server. It might just have been that, which caused the issue. In other words, I can not give you a clear instructions on what fixed it.
